### ISSUE TITLE
Question regarding using SSL BYOL as a backbone in the train code.

### ISSUE THREAD

**Issue by Kyoungrae-Noh** [Nayeong-V-Kim/LWBC#1]
Hello authors.

First of all, thank you for making an awesome paper.
I have a question regarding loading the freezed pretrained(or trained from scratch) BYOL ResNet.
From what I know, we use the BYOL ResNet on top of the MLPs which are LWBCs. 
However, from the given code of LWBC_<DATASET_NAME>.py, I cannot see which part of the code loads the weights of BYOL ResNet for reinforcing feature representation learning.

I hope that you can explain the particular location of the code w.r.t the loading of freezed weights on LWBC train code.

Thank you :)

**Comment by vaicarran** [comment]
Hello!

Thank you for your interest in our paper, and for your question about loading pretrained or trained-from-scratch BYOL ResNet weights in LWBC training code.

To clarify, after training the BYOL ResNet, we extract the feature vectors and save them as npy files. During LWBC training, we load the feature vectors from these npy files as inputs to the MLP-based models. This approach saves us from having to perform ResNet forward passes during each iteration of training, which speeds up the process considerably.

You can find the npy files on Google Drive, as specified in the readme.md file. We hope this answers your question, and please let us know if you have any further inquiries.

Thank you for your interest in our code!

**Comment by Nayeong-V-Kim** [comment]
Hello!

Thank you for your interest in our paper, and for your question about loading pretrained or trained-from-scratch BYOL ResNet weights in LWBC training code.

To clarify, after training the BYOL ResNet, we extract the feature vectors and save them as npy files. During LWBC training, we load the feature vectors from these npy files as inputs to the MLP-based models. This approach saves us from having to perform ResNet forward passes during each iteration of training, which speeds up the process considerably.

You can find the npy files on Google Drive, as specified in the readme.md file. We hope this answers your question, and please let us know if you have any further inquiries.

Thank you for your interest in our code!
